sudo: required
services: 
  -docker


script:
  - docker build -t mannydesigns/node .
  - docker images mannydesigns/node

before_deploy:
 - docker login -u <khunglongxanh9999> -p <123456789,>

 deploy:
  provider: script
  script: pocker push mannydesigns/node
  on: 
    branch: master

